/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../src/components/AppLink/index.vue')['default']
    AppLogo: typeof import('./../src/layouts/components/AppLogo/index.vue')['default']
    AppMain: typeof import('./../src/layouts/components/AppMain/index.vue')['default']
    BasicMenu: typeof import('./../src/layouts/components/Menu/BasicMenu.vue')['default']
    CommonWrapper: typeof import('./../src/components/CommonWrapper/index.vue')['default']
    DarkModeSwitch: typeof import('./../src/components/DarkModeSwitch/index.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    Fullscreen: typeof import('./../src/components/Fullscreen/index.vue')['default']
    Hamburger: typeof import('./../src/components/Hamburger/index.vue')['default']
    Login: typeof import('./../src/views/login/components/Login.vue')['default']
    MenuItem: typeof import('./../src/layouts/components/Menu/components/MenuItem.vue')['default']
    MenuItemContent: typeof import('./../src/layouts/components/Menu/components/MenuItemContent.vue')['default']
    MixTopMenu: typeof import('./../src/layouts/components/Menu/MixTopMenu.vue')['default']
    NavBar: typeof import('./../src/layouts/components/NavBar/index.vue')['default']
    NavbarActions: typeof import('./../src/layouts/components/NavBar/components/NavbarActions.vue')['default']
    Register: typeof import('./../src/views/login/components/Register.vue')['default']
    ResetPwd: typeof import('./../src/views/login/components/ResetPwd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsView: typeof import('./../src/layouts/components/TagsView/index.vue')['default']
  }
}
